### ISSUE TITLE
Wiki entry or README for adding custom tracers

### ISSUE THREAD

**Issue by KiranPanesar** [iSECPartners/Introspy-iOS#33]
I'm trying to add a tracer for a custom class in my app. Is there a wiki entry somewhere on how to do this?

**Comment by radj** [comment]
You can study the code and follow the existing class hooks. As a hint, check `src/hooks/UIPasteboardHooks.xm` and see how this file is used in `Tweak.xmi` :)

Once you've done that, you will need to make changes in [Introspy-Analyzer](https://github.com/iSECPartners/Introspy-Analyzer) (if you need the HTML report) to accommodate your new method and class names. For that part, you can review how `UIPasteboard` is also used.

**Comment by KiranPanesar** [comment]
Ok cool. I can add an entry to the wiki on adding custom tracers once I've figured it out. Seems like it would be useful.
