### ISSUE TITLE
dependency problems prevent configuration

### ISSUE THREAD

**Issue by juneJuly** [iSECPartners/Introspy-iOS#36]
make package goes good
but install get error as below,what's the problem

Selecting previously deselected package com.isecpartners.introspy.
(Reading database ... 2222 files and directories currently installed.)
Unpacking com.isecpartners.introspy (from /tmp/_theos_install.deb) ...
dpkg: dependency problems prevent configuration of com.isecpartners.introspy:
 com.isecpartners.introspy depends on applist; however:
  Package applist is not installed.
dpkg: error processing com.isecpartners.introspy (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 com.isecpartners.introspy
make: *** [internal-install] Error 1

**Comment by radj** [comment]
Via SSH, run `apt-get -f install` to resolve dependencies.

Or open into Cydia and install applist first before installing Introspy.

**Comment by juneJuly** [comment]
@radj thx a lot1

**Comment by radj** [comment]
@juneJuly Did it work? If it did, kindly close the ticket :)

**Comment by juneJuly** [comment]
@radj  yes,its worked.   thz!
